# Emoji Configuration for Planaria
# Centralized location for all emoji definitions used in the UI

# Sidebar Navigation
SIDEBAR_PLAN = "📋"
SIDEBAR_NEW_LOAD = "🆕"
SIDEBAR_PEOPLE = "👥"
SIDEBAR_CURRENT_STATE = "💰"
SIDEBAR_INCOME = "💵"
SIDEBAR_ASSETS = "🏦"
SIDEBAR_LIABILITIES = "💳"
SIDEBAR_EXPENSES = "💸"
SIDEBAR_FUTURE_EVENTS = "🔮"
SIDEBAR_FUTURE_EVENTS_LINK = "🎯"
SIDEBAR_RESULTS = "📊"
SIDEBAR_CASH_FLOW = "💹"
SIDEBAR_NET_WORTH = "📈"
SIDEBAR_RATIOS = "📉"

# Action Buttons
BUTTON_UPDATE = "🔄"
BUTTON_SAVE = "💾"
BUTTON_DELETE = "🗑️"
BUTTON_ADD_PERSON = "👤"
BUTTON_ADD_INCOME = "💵"
BUTTON_ADD_LIABILITY = "💳"
BUTTON_ADD_NECESSARY_EXPENSE = "💸"
BUTTON_ADD_DISCRETIONARY_EXPENSE = "🎯"
BUTTON_ADD_ASSET = "🏦"
BUTTON_ADD_HOME = "🏠"
BUTTON_ADD_401K = "💰"
BUTTON_ADD_CAR = "🚗"
BUTTON_ADD_PENSION = "🏦"

# Future Events
BUTTON_BUY_HOME = "🏠"
BUTTON_BUY_CAR = "🚗"
BUTTON_HAVE_CHILD = "👶"
BUTTON_COMBINE_EXPENSES = "🔗"
BUTTON_DELETE_CHILD = "🗑️"
BUTTON_GET_MARRIED = "💍"

# Page Tabs
TAB_BALANCE_SHEET = "📊"
TAB_NET_WORTH = "📈"
TAB_RETIREMENT = "🏖️"
TAB_ANNUAL_BUDGET = "💰"
TAB_CASH_FLOW_DIAGRAM = "🌊"
TAB_EXPENSE_PROJECTIONS = "📈"
TAB_RATIOS = "📊" 