#############################
# Streamlit config (spec-only)
# See: https://docs.streamlit.io/develop/api-reference/configuration/config.toml
#############################

[client]
showSidebarNavigation = false

[theme]
# Core supported theme keys
primaryColor = "#1e3a8a"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#1f2937"
# font accepts only: "sans serif", "serif", or "monospace"
# We'll style custom font stacks via CSS.
font = "sans serif"

[server]
# Server configuration